version: '3'

services:
  django_api:
    build: django_api
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django_api/code
    ports:
      - "8000:8000"
    links:
      - "postgres"
  postgres:
    image: postgres:9
    environment:
      POSTGRES_PASSWORD: asdqwe123
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    links:
      - "postgres"