# Generated by Django 2.0.1 on 2018-01-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('inventory', '0001_initial'), ('inventory', '0002_city'), ('inventory', '0003_auto_20180115_1952'), ('inventory', '0004_company_city'), ('inventory', '0005_complain')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete='cascade', to='inventory.Country')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('state', models.ForeignKey(on_delete='cascade', to='inventory.State')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Consumer',
                'verbose_name_plural': 'Consumers',
            },
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=254),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.ForeignKey(default=1, on_delete='cascade', to='inventory.City'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('city', models.ForeignKey(on_delete='cascade', to='inventory.City')),
                ('company', models.ForeignKey(on_delete='cascade', to='inventory.Company')),
                ('consumer', models.ForeignKey(on_delete='cascade', to='inventory.Consumer')),
            ],
            options={
                'verbose_name': 'Complain',
                'verbose_name_plural': 'Complains',
            },
        ),
    ]
