# Generated by Django 2.0.1 on 2018-01-16 03:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial_sqashed_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
