# Generated by Django 2.0.1 on 2018-01-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_complain_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete='cascade', related_name='cities', to='inventory.State'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.ForeignKey(on_delete='cascade', related_name='companies', to='inventory.City'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='city',
            field=models.ForeignKey(on_delete='cascade', related_name='complains', to='inventory.City'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='company',
            field=models.ForeignKey(on_delete='cascade', related_name='complains', to='inventory.Company'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='consumer',
            field=models.ForeignKey(on_delete='cascade', related_name='complains', to='inventory.Consumer'),
        ),
        migrations.AlterField(
            model_name='state',
            name='country',
            field=models.ForeignKey(on_delete='cascade', related_name='states', to='inventory.Country'),
        ),
    ]
