# Generated by Django 2.0.1 on 2018-01-25 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20180125_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['-id'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
    ]
