# Generated by Django 2.0.1 on 2018-01-25 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20180125_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-id'], 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-id'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='complain',
            options={'ordering': ['-id'], 'verbose_name': 'Complain', 'verbose_name_plural': 'Complains'},
        ),
        migrations.AlterModelOptions(
            name='consumer',
            options={'ordering': ['-id'], 'verbose_name': 'Consumer', 'verbose_name_plural': 'Consumers'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['-id'], 'verbose_name': 'State', 'verbose_name_plural': 'States'},
        ),
    ]
